export const genderData = [
    { name: 'Male', value: 55, color: '#9370DB' },
    { name: 'Female', value: 45, color: '#E91E63' },
];

export const ageData = [
    { age: '17-20', male: 70, female: 95 },
    { age: '21-25', male: 45, female: 60 },
    { age: '26-30', male: 30, female: 35 },
    { age: '31-35', male: 25, female: 30 },
    { age: '36-40', male: 18, female: 22 },
    { age: '41-45', male: 65, female: 70 },
    { age: '50+', male: 50, female: 55 },
];

export const newUsersData = [
    { name: 'Jan', users: 120 },
    { name: 'Feb', users: 150 },
    { name: 'Mar', users: 100 },
    { name: 'Apr', users: 180 },
    { name: 'May', users: 160 },
    { name: 'Jun', users: 200 },
];

export const activeUsersData = [
    { name: 'Male', value: 123456, color: '#9370DB' },
    { name: 'Female', value: 100789, color: '#E91E63' },
    { name: 'Inactive', value: 75789, color: '#FFCE56' },
];

export const staticUsers = [
    {
        _id: '1',
        firstName: 'Alice',
        lastName: 'Johnson',
        email: 'alice.johnson@example.com',
        phone: '+1-234-567-890',
        dob: '1992-08-15',
        designation: 'UI Designer',
        connectedWallet: 'PayPal',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/women/1.jpg',
        createdAt: '2024-12-01'
    },
    {
        _id: '2',
        firstName: 'Mark',
        lastName: 'Smith',
        email: 'mark.smith@example.com',
        phone: '+1-987-654-321',
        dob: '1988-04-22',
        designation: 'Backend Developer',
        connectedWallet: 'Zelle',
        accountBlocked: true,
        image: 'https://randomuser.me/api/portraits/men/2.jpg',
        createdAt: '2025-01-10'
    },
    {
        _id: '3',
        firstName: 'Sofia',
        lastName: 'Lopez',
        email: 'sofia.lopez@example.com',
        phone: '+1-456-789-012',
        dob: '1995-11-02',
        designation: 'Marketing Manager',
        connectedWallet: 'Venmo',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/women/3.jpg',
        createdAt: '2025-02-18'
    },
    {
        _id: '4',
        firstName: 'David',
        lastName: 'Nguyen',
        email: 'david.nguyen@example.com',
        phone: '+1-321-654-987',
        dob: '1990-03-30',
        designation: 'Product Manager',
        connectedWallet: 'Apple Pay',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/men/4.jpg',
        createdAt: '2025-03-10'
    },
    {
        _id: '5',
        firstName: 'Emma',
        lastName: 'Brown',
        email: 'emma.brown@example.com',
        phone: '+1-222-333-4444',
        dob: '1993-07-19',
        designation: 'Frontend Developer',
        connectedWallet: 'Payoneer',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/women/5.jpg',
        createdAt: '2025-04-05'
    },
    {
        _id: '6',
        firstName: 'James',
        lastName: 'Wilson',
        email: 'james.wilson@example.com',
        phone: '+1-555-666-7777',
        dob: '1985-09-12',
        designation: 'DevOps Engineer',
        connectedWallet: 'CashApp',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/men/6.jpg',
        createdAt: '2025-04-10'
    },
    {
        _id: '7',
        firstName: 'Olivia',
        lastName: 'Martinez',
        email: 'olivia.martinez@example.com',
        phone: '+1-444-555-6666',
        dob: '1991-05-21',
        designation: 'HR Specialist',
        connectedWallet: 'Venmo',
        accountBlocked: true,
        image: 'https://randomuser.me/api/portraits/women/7.jpg',
        createdAt: '2025-04-12'
    },
    {
        _id: '8',
        firstName: 'Liam',
        lastName: 'Garcia',
        email: 'liam.garcia@example.com',
        phone: '+1-777-888-9999',
        dob: '1987-03-14',
        designation: 'QA Engineer',
        connectedWallet: 'Zelle',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/men/8.jpg',
        createdAt: '2025-04-15'
    },
    {
        _id: '9',
        firstName: 'Ava',
        lastName: 'Davis',
        email: 'ava.davis@example.com',
        phone: '+1-888-999-0000',
        dob: '1994-10-10',
        designation: 'Content Strategist',
        connectedWallet: 'Apple Pay',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/women/9.jpg',
        createdAt: '2025-04-17'
    },
    {
        _id: '10',
        firstName: 'Noah',
        lastName: 'Lee',
        email: 'noah.lee@example.com',
        phone: '+1-666-777-8888',
        dob: '1990-06-08',
        designation: 'UI/UX Designer',
        connectedWallet: 'PayPal',
        accountBlocked: true,
        image: 'https://randomuser.me/api/portraits/men/10.jpg',
        createdAt: '2025-04-20'
    },
    {
        _id: '11',
        firstName: 'Mia',
        lastName: 'Clark',
        email: 'mia.clark@example.com',
        phone: '+1-333-444-5555',
        dob: '1996-01-02',
        designation: 'Support Engineer',
        connectedWallet: 'Payoneer',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/women/11.jpg',
        createdAt: '2025-04-22'
    },
    {
        _id: '12',
        firstName: 'William',
        lastName: 'Walker',
        email: 'william.walker@example.com',
        phone: '+1-999-000-1111',
        dob: '1989-11-11',
        designation: 'Data Analyst',
        connectedWallet: 'Zelle',
        accountBlocked: true,
        image: 'https://randomuser.me/api/portraits/men/12.jpg',
        createdAt: '2025-04-24'
    },
    {
        _id: '13',
        firstName: 'Isabella',
        lastName: 'Hall',
        email: 'isabella.hall@example.com',
        phone: '+1-101-202-3030',
        dob: '1992-04-18',
        designation: 'Graphic Designer',
        connectedWallet: 'CashApp',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/women/13.jpg',
        createdAt: '2025-04-26'
    },
    {
        _id: '14',
        firstName: 'Benjamin',
        lastName: 'Allen',
        email: 'benjamin.allen@example.com',
        phone: '+1-303-404-5050',
        dob: '1986-02-20',
        designation: 'Cloud Architect',
        connectedWallet: 'PayPal',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/men/14.jpg',
        createdAt: '2025-04-28'
    },
    {
        _id: '15',
        firstName: 'Emily',
        lastName: 'Young',
        email: 'emily.young@example.com',
        phone: '+1-606-707-8080',
        dob: '1997-12-07',
        designation: 'Research Analyst',
        connectedWallet: 'Venmo',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/women/15.jpg',
        createdAt: '2025-04-30'
    },
    {
        _id: '16',
        firstName: 'Henry',
        lastName: 'King',
        email: 'henry.king@example.com',
        phone: '+1-909-808-7070',
        dob: '1983-08-25',
        designation: 'Security Engineer',
        connectedWallet: 'Zelle',
        accountBlocked: true,
        image: 'https://randomuser.me/api/portraits/men/16.jpg',
        createdAt: '2025-05-01'
    },
    {
        _id: '17',
        firstName: 'Charlotte',
        lastName: 'Scott',
        email: 'charlotte.scott@example.com',
        phone: '+1-505-606-7070',
        dob: '1991-11-09',
        designation: 'Social Media Manager',
        connectedWallet: 'Apple Pay',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/women/17.jpg',
        createdAt: '2025-05-02'
    },
    {
        _id: '18',
        firstName: 'Daniel',
        lastName: 'Green',
        email: 'daniel.green@example.com',
        phone: '+1-707-808-9090',
        dob: '1984-05-15',
        designation: 'Business Analyst',
        connectedWallet: 'Payoneer',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/men/18.jpg',
        createdAt: '2025-05-04'
    },
    {
        _id: '19',
        firstName: 'Amelia',
        lastName: 'Baker',
        email: 'amelia.baker@example.com',
        phone: '+1-808-909-1010',
        dob: '1998-02-03',
        designation: 'Sales Executive',
        connectedWallet: 'CashApp',
        accountBlocked: false,
        image: 'https://randomuser.me/api/portraits/women/19.jpg',
        createdAt: '2025-05-06'
    },
    {
        _id: '20',
        firstName: 'Logan',
        lastName: 'Adams',
        email: 'logan.adams@example.com',
        phone: '+1-101-111-1212',
        dob: '1982-07-29',
        designation: 'Technical Lead',
        connectedWallet: 'Venmo',
        accountBlocked: true,
        image: 'https://randomuser.me/api/portraits/men/20.jpg',
        createdAt: '2025-05-08'
    }
];

const staticTransactions = [
    {
        _id: 'txn_001',
        createdAt: '2025-06-20T12:00:00Z',
        senderName: 'Alice Johnson',
        senderEmail: 'alice.johnson@example.com',
        receiverName: 'Mark Smith',
        receiverEmail: 'mark.smith@example.com',
        amount: 150.00,
        paymentType: 'Deposit',
        status: 'Pending',
    },
    {
        _id: 'txn_002',
        createdAt: '2025-06-21T09:30:00Z',
        senderName: 'Sofia Lopez',
        senderEmail: 'sofia.lopez@example.com',
        receiverName: 'David Nguyen',
        receiverEmail: 'david.nguyen@example.com',
        amount: 250.00,
        paymentType: 'Withdraw',
        status: 'Approved',
    },
    {
        _id: 'txn_003',
        createdAt: '2025-06-22T15:45:00Z',
        senderName: 'Emma Brown',
        senderEmail: 'emma.brown@example.com',
        receiverName: 'James Wilson',
        receiverEmail: 'james.wilson@example.com',
        amount: 75.00,
        paymentType: 'Transfer',
        status: 'Declined',
    }
];
